### ISSUE TITLE
Clicking scrollbar triggers blur in IE

### ISSUE THREAD

**Issue by smjiko** [alphagov/accessible-autocomplete#331] opened 2019-02-26 11:20 UTC
In IE11, using the mouse/trackpad to scroll the list of suggestions seems to trigger the blur event almost immediately. I've done some investigating into the issue and it appears that this issue is not unique to autocomplete implementations in IE, and generally there are differing ways to tackle the issue that are dependent on the implemention.

**Comment by vanitabarrett** [comment] 2022-01-05 16:46
Thanks for raising this issue @smjiko. I'm going to close this issue as I believe it might be a duplicate of https://github.com/alphagov/accessible-autocomplete/issues/416. If I'm wrong and this is a separate issue, please re-open the issue and provide some replications steps/screenshots/videos so we can see the issue in action. Thanks.

**Closed by vanitabarrett** 2022-01-05 16:46 UTC
Labels: 🐛 bug
