### ISSUE TITLE
Mouse clicks are getting hijacked since 2.0.2

### ISSUE THREAD

**Issue by robbiepaul** [alphagov/accessible-autocomplete#414] opened 2020-02-03 14:29 UTC
We're getting a failing build when updating to 2.0.2. We're seeing any clicks below the autocomplete field being hijacked once, if you click again a second time it works. 

I've tested it in Chrome, Safari and Firefox and they all show the same behaviour.

### Steps to reproduce:

- Include a link after the accessible-autocomplete field (eg. in a footer)
- Start typing something to get some results (but don't click any of them)
- Click the link that you included

### Expected behaviour

- The browser goes to the link

### Actual behaviour

- The browser doesn't go to the link

Happy to provide our real-world use case if it helps.

**Comment by nickcolley** [comment] 2020-02-03 14:32
Hey @robbiepaul,

Any real world example you can share easily would be helpful to reproduce this.

Thanks :)

**Comment by robbiepaul** [comment] 2020-02-03 14:45
Thanks for the quick response @nickcolley.

Here's our use case, although it's currently on 2.0.1. The follow steps will fail with 2.0.2:

- If you go to https://www.claim-additional-teaching-payment.service.gov.uk/student-loans/claim
- Then choose "In or after the academic year 2013 to 2014"
- Start typing a school name (eg. "Hampstead School")
- Click "Search" without clicking a school
- You see a separate search results page

I tested it locally with 2.0.2 and even clicking any links in the footer won't work on the first attempt, the second works fine.

Here's an example of a failing spec: https://github.com/DFE-Digital/dfe-teachers-payment-service/blob/dependabot/npm_and_yarn/accessible-autocomplete-2.0.2/spec/features/school_search_spec.rb#L87-L102 
(duplicating the line `click_on "Search"` makes the test pass because it's the second click as described above)

**Comment by nickcolley** [comment] 2020-02-05 16:29
I have created an application that reproduces this issue:

https://accessible-autocomplete-issue-414.glitch.me/

It seems to be when the component is used without the 'overlayMenu' feature, as when you click away from the component it moves the button from underneath the mouse and therefore stops the button from clicking.

If I'm correct it's not that the component is hijacking mouse clicks (for example with event listeners), it's that the page scrolls stopping the click.

**Comment by nickcolley** [comment] 2020-02-05 17:05
In order to fix your tests, you can hide the component's menu before trying to press the submit button, for example by sending the 'ESC' button keypress.

You could also consider using the [`displayMenu: 'overlay'` option](https://alphagov.github.io/accessible-autocomplete/examples/#tt-minLength) which would prevent the component from changing the height of the page, but we think you'd still need to change your test as you wouldnt be able to press the button as it would be obscured by the menu.

This might be better from a user point of view since they will need to make a decision by pressing an option, but we're not sure of the constraints of your page, so up to you to figure out.

The reason you didn't see this behaviour was because of a timeout that [we removed to fix another bug ](https://github.com/alphagov/accessible-autocomplete/pull/410).

We're going to close this as we think we've done everything we can but if you've got any suggestions to resolve this another way we'd be open to feedback, so feel free to reopen. :) 

Thanks for the great steps to reproduce, it was very helpful.

**Closed by nickcolley** 2020-02-05 17:05 UTC
Labels: awaiting-triage

**Comment by robbiepaul** [comment] 2020-02-07 17:02
Thanks for doing the investigation @nickcolley. I've renamed the issue to be more accurate incase others are searching for the same thing.

I've spent a bit of my Friday time looking at ways round this issue and propose we modify the blur event handlers to prevent closing the option menu if a clickable element has been clicked.

Something like:

```js
handleInputBlur (event) {
  const { focused, menuOpen, options, query, selected } = this.state
  const focusingAnOption = focused !== -1
  if (!focusingAnOption) {
    const keepMenuOpen = menuOpen && (isIosDevice() || isInteractableElement(event.relatedTarget))
    const newQuery = isIosDevice() ? query : this.templateInputValue(options[selected])
    this.handleComponentBlur({
      menuOpen: keepMenuOpen,
      query: newQuery
    })
  }
}

function isInteractableElement (element) {
  return element &&
    (
      element.nodeName === 'BUTTON' ||
      element.nodeName === 'A' ||
      (element.nodeName === 'INPUT' && element.type === 'submit')
    )
}
```
`event.relatedTarget` seems to have good enough browser support to achieve this: https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget

If you're open to the suggestion I'd be happy to open a PR.

**Comment by nickcolley** [comment] 2020-02-07 17:11
@robbiepaul with your proposal what would happen when tabbing to another clickable input? Would the menu stay open?

**Comment by robbiepaul** [comment] 2020-02-07 17:16
@nickcolley Ah I didn't know that about IE11.

Yeah the menu would stay open after tabbing to a clickable element, do you have concerns about it?

**Comment by nickcolley** [comment] 2020-02-07 17:17
I think that could break other functionality like displayMode: 'overlay' and autoselect: 'true'. It doesnt seem correct for an input to stay open when it's no longer being interacted with.

**Comment by robbiepaul** [comment] 2020-02-07 17:20
Ahh I see, I'll time box some time to have a look at it and make another suggestion next Friday 👍

**Comment by nickcolley** [comment] 2020-02-07 17:20
Thanks Robbie, super helpful :)

**Comment by nickcolley** [comment] 2020-02-07 17:21
Scenario I'm thinking of with overlay:

You tab to an input underneath it and you can't see what you're doing because they overlay menu is in the way.
