### ISSUE TITLE
Option to always display menu when input is focussed

### ISSUE THREAD

**Issue by OliverJAsh** [alphagov/accessible-autocomplete#141] opened 2017-05-17 08:01 UTC
Hi there,

Thanks for the fantastic project.

I want to use this as a replacement/enhancement for `select`. However, none of the examples I can find will show all the results before the user has typed anything. It would be useful if the menu was opened as soon as the input was focussed, much like clicking on a `select` opens the full list. The user could then scroll to find their result, or type to filter it.

Is this behaviour supported using existing functionality?

This would be similar to the [`alwaysRenderSuggestions` option provided by react-autosuggest](https://github.com/moroshko/react-autosuggest#alwaysRenderSuggestionsProp).

Thanks,
Oliver

**Comment by tvararu** [comment] 2017-05-17 09:10
Hi @OliverJAsh! Thanks for the feedback.

Your issue is quite similar to https://github.com/alphagov/accessible-autocomplete/issues/31. No, it's not supported today, but we definitely want to have this.

**Comment by OliverJAsh** [comment] 2017-05-17 09:23
Great, thanks for the quick feedback! I will consider contributing when I come to use it.

**Comment by tvararu** [comment] 2017-05-17 09:29
@OliverJAsh haha, wasn't trying to trip you into that! I will eventually get to it myself.

This feature should be simple to implement.

I'm happy to provide further guidance for someone trying to understand the codebase and submit it as a first contribution. 👍

**Comment by joelanman** [comment] 2017-06-01 09:51
I'm looking into this.

The problem I've come across is that currently there is no default `source` function. When we want to show options in this scenario, if we call `source` with a blank input, nothing returns. Since `source` is a function that comes from the user, we cannot modify it to say 'in this situation, return all results'.

One solution might be to change what accessibleAutocomplete accepts. Instead of a single `source` function, it could be `options` and `searchFunction`, with `searchFunction` being optional as we would have a simple default.

This would then give us access to all the options, and bring the default searchFunction under our control, and we could provide this 'showAllOptions' feature.

**Comment by tvararu** [comment] 2017-06-01 09:58
> When we want to show options in this scenario, if we call source with a blank input, nothing returns. Since source is a function that comes from the user, we cannot modify it to say 'in this situation, return all results'.

@joelanman I think it's fine if we guide users to do that. The autocomplete should call `source` with an empty string, and whatever `source` returns is fair play. The user should have complete control over the behaviour of `source` so they can customise it based on their needs.

The current behaviour of the autocomplete is a bit of a double standard, as `minLength: 0` and `minLength: 1` mean the same thing. The docs on `minLength` are not completely true: https://github.com/alphagov/accessible-autocomplete#minlength-default-0

> One solution might be to change what accessibleAutocomplete accepts. Instead of a single source function, it could be options and searchFunction, with searchFunction being optional as we would have a simple default.

That's out of scope for this, but it's another feature we'd like! 😄  https://github.com/alphagov/accessible-autocomplete/issues/115

**Comment by vanitabarrett** [comment] 2022-01-06 12:19
I'm going to close this issue as I believe this has been implemented in the `showAllValues` option that can be used with this component. If you think this hasn't been implemented, please re-open the issue and provide replication steps so we're able to reproduce the issue.

**Closed by vanitabarrett** 2022-01-06 12:19 UTC
Labels: feature request, help wanted
